---

- hosts: all
  remote_user: root
  vars_files:
    - 'defaults/main.yml'

  roles:
    - { role: rvm_io.rvm1-ruby, sudo: True }
    - sbitmedia.fail2ban
    - { role: geerlingguy.firewall, sudo: True }

  tasks:
    - include: 'tasks/main.yml'
    - include: 'tasks/nginx.yml'

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
    - name: restart mysql
      service: name=mysqld state=restarted
